Repository Bob-Lion/React-Web-Market, pull requests merged in 2023-03, with the labels that each got.

#6 fix: update isuue template
  .github/ISSUE_TEMPLATE/custom.md
Labels: ⚙️ Setting

#4 이슈 템플릿 Label 재설정
  .github/ISSUE_TEMPLATE/custom.md
Labels: ⚙️ Setting

#5 이슈 템플릿 Assignees 재설정
  .github/ISSUE_TEMPLATE/custom.md
Labels: ⚙️ Setting

#24 [Feat] ProductList Accordion 상태관리 부분 및 카테고리 더보기 제외 중간 완성
  public/ProductListImage/Arrow.svg
  public/ProductListImage/Check_off.svg
  public/ProductListImage/Check_on.svg
  public/ProductListImage/resetButton.svg
  src/app/App.jsx
  src/app/App.module.scss
  src/components/ProductListNav/ AccordionFillter.jsx
  src/components/ProductListNav/Accordion.jsx
  src/components/ProductListNav/AccordionList.jsx
  src/components/ProductListNav/AccordionSet.jsx
  src/components/ProductListNav/NavDetail.jsx
  src/components/ProductListNav/ProductListNav.jsx
  src/components/ProductListNav/ProductListNav.module.scss
  src/main.jsx
  src/pages/Home/Home.jsx
  src/pages/Home/Home.module.scss
  src/pages/ProductList/ProductList.jsx
  src/pages/ProductList/ProductList.module.scss
  src/styles/normalize.scss
  src/styles/reset.scss
  src/utils/index.js
  src/utils/product_list/index.js
  src/utils/product_list/korean_pre_sort.js
  src/utils/product_list/many_product_sort.js
  src/utils/product_list/name_sort.js
  src/utils/product_list/priceSort.js
  vite.config.js
Labels: ✨ Feature

#33 [Feat] Footer 컴포넌트 구현
  jsconfig.json
  public/img/Footer/blog.svg
  public/img/Footer/facebook.svg
  public/img/Footer/instagram.svg
  public/img/Footer/logo_isms.svg
  public/img/Footer/logo_privacy.svg
  public/img/Footer/logo_tosspayments.svg
  public/img/Footer/logo_wooriBank.svg
  public/img/Footer/naverpost.svg
  public/img/Footer/youtube.svg
  src/components/Footer/Footer.jsx
  src/components/Footer/Footer.module.scss
Labels: ✨ Feature

#38 [Feat] 리스트 선택 초기화 구현
  src/@atom/accordion/accordionBenefit.js
  src/@atom/accordion/accordionBrand.js
  src/@atom/accordion/accordionCategory.js
  src/@atom/accordion/accordionPrice.js
  src/@atom/accordion/accordionType.js
  src/@atom/accordion/benefitSelect.js
  src/@atom/accordion/brandSelect.js
  src/@atom/accordion/categorySelect.js
  src/@atom/accordion/priceSelect.js
  src/@atom/accordion/productListResetBtn.js
  src/@atom/accordion/selectList.js
  src/@atom/accordion/typeSelect.js
  src/components/ProductListNav/Accordion.jsx
  src/components/ProductListNav/AccordionFillter.jsx
  src/components/ProductListNav/AccordionList.jsx
  src/components/ProductListNav/AccordionSet.jsx
  src/components/ProductListNav/ProductListNav.module.scss
Labels: ✨ Feature

#40 [Feat, Style] 파이어베이스 유틸함수 수정사항 적용 및 누락파일 추가 / ProductCard 컴포넌트 스타일 수정
  src/components/ProductCarousel/ProductCarousel.jsx
  src/components/ProductCarousel/ProductCarousel.module.scss
  src/components/ProductCarousel/ProductCarousel.scss
  src/firebase/README.md
  src/firebase/app.js
  src/firebase/auth/README.md
  src/firebase/firestore/README.md
  src/firebase/firestore/index.js
  src/firebase/firestore/useDataState.js
  src/firebase/firestore/useUpdateData.js
  src/firebase/firestore/useWriteBatchData.js
  src/firebase/storage/README.md
  src/firebase/storage/index.js
Labels: ✨ Feature

#39 [Feat] 카테고리 및 브랜드 더보기 모달창 구현
  public/ProductListImage/ModalClose.svg
  src/components/ProductListNav/AccordionList.jsx
  src/components/ProductListNav/AccordionSet.jsx
  src/components/ProductListNav/BrandSortBtn.jsx
  src/components/ProductListNav/NavDetailModal.jsx
  src/components/ProductListNav/ProductListNav.module.scss
  src/styles/global.scss
  src/styles/normalize.scss
Labels: ✨ Feature

#43 [Feat] PopupAd 컴포넌트 구현
  public/img/PopupAd/popup-image.svg
  src/components/PopupAd/PopupAd.jsx
  src/components/PopupAd/PopupAd.module.scss
Labels: ✨ Feature

#45 [Feat] 장바구니 팝업 마크업 및 기본 기능 구현
  src/@atom/addCartPopup/popupVisible.js
  src/app/App.jsx
  src/components/AddCart/AddCartPopup.jsx
  src/components/AddCart/AddCartPopup.module.scss
Labels: ✨ Feature

#46 [Feat] Pagination 버튼 구현
  package-lock.json
  package.json
  src/components/Pagination/Pagination.module.scss
  src/components/Pagination/PaginationPost.jsx
  src/components/Pagination/Posts.jsx
  src/db/data.json
  src/styles/reset.scss
Labels: ✨ Feature

#47 [Feat] 장바구니 팝업창 로컬스토리지에 해당 상품 docId 및 수량 저장
  src/app/App.jsx
  src/components/AddCart/AddCartPopup.jsx
Labels: ✨ Feature

#53 [feat] Header와 MiniHeader 구현 (#10)
  package-lock.json
  package.json
  public/Header/cartIcon.svg
  public/Header/categoryAquaticProduct.svg
  public/Header/categoryBaby.svg
  public/Header/categoryBakery.svg
  public/Header/categoryDrink.svg
  public/Header/categoryElectronicProduct.svg
  public/Header/categoryFruit.svg
  public/Header/categoryGiftIcon.svg
  public/Header/categoryHair.svg
  public/Header/categoryHealthFood.svg
  public/Header/categoryHouseholdItem.svg
  public/Header/categoryIcon.svg
  public/Header/categoryKitchenWare.svg
  public/Header/categoryMeat.svg
  public/Header/categoryPet.svg
  public/Header/categorySalad.svg
  public/Header/categorySeasoning.svg
  public/Header/categorySkinCare.svg
  public/Header/categorySnack.svg
  public/Header/categorySoup.svg
  public/Header/categoryTraditionalLiquor.svg
  public/Header/categoryTravel.svg
  public/Header/categoryVegetable.svg
  public/Header/categoryWine.svg
  public/Header/customerServiceIcon.svg
  public/Header/favoriteIcon.svg
  public/Header/logo.svg
  public/Header/mapIcon.svg
  public/Header/miniHeaderSearchIcon.svg
  public/Header/newLogo.svg
  public/Header/searchIcon.svg
  public/Header/topBannerCloseBtnIcon.svg
  src/app/App.module.scss
  src/components/Header/Header.jsx
  src/components/Header/Header.module.scss
  src/components/Header/HeaderCategory.jsx
  src/components/Header/HeaderCategoryNav.jsx
  src/components/Header/HeaderIcon.jsx
  src/components/Header/HeaderNav.jsx
  src/components/Header/HeaderTopbanner.jsx
  src/components/Header/MiniHeader.jsx
  src/firebase/app.js
  src/firebase/auth/index.js
  src/firebase/auth/useAuthState.js
  src/firebase/auth/useSignUp.js
  src/styles/normalize.scss
Labels: ✨ Feature

#56 [Feat, Style] 현재 선택된 상품에 대한 atom state 생성 및 global.scss 파일 타입변경
  src/@atom/currentProductState.js
  src/app/App.scss
  src/components/AddCartShortcutBtn/AddCartShortcutBtn.jsx
  src/components/AddCartShortcutBtn/AddCartShortcutBtn.module.scss
Labels: ✨ Feature

#60 [Feat] ProductGruop 상품 목록 페이지 구현
  src/components/ProductGroup/ProductGroup.jsx
  src/components/ProductGroup/ProductGroup.module.scss
  src/components/ProductGroup/ProductGroup.scss
  src/components/ProductGroup/ProductGroupFilter.jsx
Labels: ✨ Feature

#61 [Feat] 장바구니 페이지 구조 완성
  public/ProductListImage/Check_on.svg
  public/icons/web-icons/Frozen.svg
  public/icons/web-icons/Normal.svg
  public/icons/web-icons/Refrigerated.svg
  public/icons/web-icons/Search.svg
  src/@atom/accordion/accordionSelectListState.js
  src/@atom/accordion/benefitSelectState.js
  src/@atom/accordion/brandSelectState.js
  src/@atom/accordion/categorySelectState.js
  src/@atom/accordion/priceSelectState.js
  src/@atom/accordion/productCheckResetState.js
  src/@atom/accordion/productResetBtnState.js
  src/@atom/accordion/selectList.js
  src/@atom/accordion/typeSelectState.js
  src/@atom/addCartPopup/cartPopupVisibleState.js
  src/@atom/cartPage/cartTotalSeletState.js
  src/@atom/cartPage/selectInfoState.js
  src/@atom/cartPage/selectTotalPriceState.js
  src/@atom/productDataState.js
  src/app/App.jsx
  src/app/App.scss
  src/components/AddCart/AddCartPopup.jsx
  src/components/AddCart/AddCartPopup.module.scss
  src/components/CartPageAccordion/CartPageAccordion.jsx
  src/components/CartPageAccordion/CartPageAccordion.module.scss
  src/components/CartPageAccordion/CartPageProduct.jsx
  src/components/CartPageAccordion/CartPageSet.jsx
  src/components/CartPageAccordion/CartPageStoringWay.jsx
  src/components/CartPageAccordion/ProductSelectCtrl.jsx
  src/components/CartPageCredit/CartPageCredit.jsx
  src/components/CartPageCredit/CartPageCredit.module.scss
  src/components/Header/Header.jsx
  src/components/Pagination/PaginationPost.jsx
  src/components/ProductListNav/Accordion.jsx
  src/components/ProductListNav/AccordionFillter.jsx
  src/components/ProductListNav/AccordionList.jsx
  src/components/ProductListNav/AccordionSet.jsx
  src/components/ProductListNav/BrandSortBtn.jsx
  src/components/ProductListNav/ProductListNav.jsx
  src/components/ProductListNav/ProductListNav.module.scss
  src/pages/ProductList/ProductList.module.scss
  src/pages/cartPage/CartPage.jsx
  src/pages/cartPage/CartPage.module.scss
  src/utils/product_list/priceSort.js
  src/utils/storingWay/storingWaySort.js
Labels: ✨ Feature

#65 [feat] Header Category Menu 구현 (#11)
  src/components/Header/Header.jsx
  src/components/Header/Header.module.scss
  src/components/Header/HeaderCategory.jsx
  src/components/Header/HeaderCategoryNav.jsx
  src/components/Header/HeaderCategorySideNav.jsx
  src/components/Header/HeaderNav.jsx
  src/components/Header/MiniHeader.jsx
Labels: ✨ Feature

#69 [Feat] 장바구니 페이지 전체선택 제외 상태관리 완료
  src/@atom/cartPage/cartDataState.js
  src/@atom/cartPage/localDataRanderState.js
  src/@atom/cartPage/selectPriceState.js
  src/@atom/cartPage/selectTotalPriceState.js
  src/app/App.jsx
  src/components/AddCart/AddCartPopup.jsx
  src/components/CartPageAccordion/CartPageAccordion.jsx
  src/components/CartPageAccordion/CartPageAccordion.module.scss
  src/components/CartPageAccordion/CartPageProduct.jsx
  src/components/CartPageAccordion/ProductSelectCtrl.jsx
  src/components/CartPageCredit/CartPageCredit.jsx
  src/pages/cartPage/CartPage.jsx
  src/utils/filterDocId.js
  src/utils/localStorageDeleteData.js
  src/utils/priceNumberToStringNoWon.js
  src/utils/removeDuplicates.js
Labels: ✨ Feature

#73 [Fix, Feature] ProductGroup 구조 수정, ProductReview 마크업 html
  src/components/ProductGroup/ProductGroup.jsx
  src/components/ProductGroup/ProductGroup.scss
  src/components/ProductGroup/ProductGroupFilter.jsx
  src/components/ProductReview/ProductReview.jsx
  src/components/ProductReview/ProductReview.scss
  src/components/ProductReview/ProductReviewUser.jsx
Labels: 🐞 BugFix, ✨ Feature, 🔨 Refactor

#77 [feat] Header Location icon에 Hover시 팝업 구현 (#12)
  public/Header/mapIconPopupSearchIcon.svg
  public/Header/popupPointer.svg
  public/Header/triangleIcon.svg
  public/Header/userNewLogo.svg
  src/@atom/Header/loginState.js
  src/components/Header/Header.jsx
  src/components/Header/Header.module.scss
  src/components/Header/HeaderCategory.jsx
  src/components/Header/HeaderCategorySideNav.jsx
  src/components/Header/HeaderIcon.jsx
  src/components/Header/HeaderLoginPopup.jsx
  src/components/Header/HeaderNoLoginPopup.jsx
  src/components/Header/MiniHeader.jsx
Labels: 🐞 BugFix, ✨ Feature

#83 [Feat] 상품 상세정보 수량 체크 버튼 및 장바구니 담기 버튼 기능구현
  src/@atom/currentProductState.js
  src/@atom/user/currentUserState.js
  src/components/ProductInfo/ProductInfo.jsx
  src/components/ProductInfo/ProductInfo.module.scss
Labels: ✨ Feature

#84 [Feat] ProductReveiw 상품 리뷰 구현하기
  src/components/ProductReview/ProductReview.jsx
  src/components/ProductReview/ProductReview.scss
  src/components/ProductReview/ProductReviewPopup.jsx
  src/components/ProductReview/ProductReviewPopup.scss
Labels: ✨ Feature, 🌈 Style

#86 [Feat] ProductDetailPage 구현
  src/components/ProductInfo/ProductInfo.module.scss
  src/components/ProductReview/ProductReview.scss
  src/components/ProductReview/ProductReviewPopup.jsx
  src/components/ProductReview/ProductReviewPopup.scss
  src/pages/ProductDetail/ProductDetailPage.jsx
Labels: 🔨 Refactor, 🌈 Style

#88 [Refactor] ProductDetailPage Router 적용
  src/app/App.jsx
  src/components/ProductCard/ProductCard.jsx
Labels: 🔨 Refactor

#91 [Feat] 상품 리스트 정렬 더보기 팝업 스타일 수정 및 장바구니 스타일 변경
  src/@atom/accordion/modalVisibleState.js
  src/app/App.jsx
  src/components/AddCart/AddCartPopup.module.scss
  src/components/CartPageAccordion/CartPageProduct.jsx
  src/components/ProductGroup/ProductGroup.jsx
  src/components/ProductGroup/ProductGroup.scss
  src/components/ProductListNav/AccordionList.jsx
  src/components/ProductListNav/AccordionSet.jsx
  src/components/ProductListNav/NavDetailModal.jsx
  src/components/ProductListNav/ProductListNav.module.scss
  src/pages/ProductList/ProductList.module.scss
  src/pages/cartPage/CartPage.module.scss
Labels: ✨ Feature

#97 [Style] ProductDetail Review 스타일 너비 색감 수정
  src/components/ProductReview/ProductReview.scss
Labels: 🌈 Style

#103 [refactor] header 장바구니페이지로 이동하는 라우터, z-index조정
  src/components/Header/Header.jsx
  src/components/Header/Header.module.scss
  src/components/Header/HeaderIcon.jsx
  src/components/Header/MiniHeader.jsx
Labels: 🔨 Refactor

#104 [Refactor] 불필요한 주석 및 primary-color 전체 변경
  public/Header/bobLion.svg
  public/Header/categoryIcon.svg
  public/Header/logo.svg
  public/Header/mapIconPopupSearchIcon.svg
  public/Header/miniHeaderSearchIcon.svg
  public/Header/searchIcon.svg
  public/icons/Badge.svg
  public/icons/Input/Check.svg
  public/icons/Input/Radio.svg
  public/icons/logo.svg
  public/icons/web-icons/Answer.svg
  public/icons/web-icons/Arrow-1.svg
  public/icons/web-icons/Arrow-purple.svg
  public/icons/web-icons/Cart.svg
  public/icons/web-icons/Search-small.svg
  public/icons/web-icons/Squre.svg
  public/img/ProductDetail/heart-on.svg
  src/components/Footer/Footer.module.scss
  src/components/Header/Header.jsx
  src/components/Header/Header.module.scss
  src/components/Header/MiniHeader.jsx
  src/components/Pagination/Pagination.module.scss
  src/components/ProductCarousel/ProductCarousel.scss
  src/components/ProductGroup/ProductGroup.jsx
  src/components/ProductGroup/ProductGroup.module.scss
  src/components/ProductGroup/ProductGroup.scss
  src/components/ProductGroup/ProductGroupFilter.jsx
  src/components/ProductInfo/ProductInfo.module.scss
  src/components/ProductReview/ProductReview.scss
  src/components/RegisterForm/RegisterForm.jsx
  src/components/RegisterForm/RegisterForm.module.scss
  src/components/RegisterForm/RegisterFormStyledButton.module.scss
  src/pages/LoginPage/LoginPage.module.scss
  src/pages/ProductList/ProductList.jsx
Labels: ✨ Feature

#109 [Deploy] 프로젝트 배포 Router 수정
  dist/assets/index-5eba9b59.js
  dist/index.html
  src/main.jsx
Labels: 🌏 deploy

#116 [Feat] 로그인 유무에 따른 ui 변화 작업
  src/components/AddCart/AddCartPopup.jsx
  src/components/CartPageAccordion/CartPageProduct.jsx
  src/components/CartPageAccordion/ProductSelectCtrl.jsx
  src/components/CartPageCredit/CartPageCredit.jsx
  src/components/CartPageCredit/CartPageCredit.module.scss
  src/components/ProductInfo/ProductInfo.jsx
  src/pages/cartPage/CartPage.jsx
  src/utils/mergeObjects.js
Labels: ✨ Feature
